# Generated by Django 5.0.1 on 2024-02-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='mavsum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='davlat',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
